// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtrD2I_E6sGbqsRtnCYL0-p4IKKIkITRM',
    appId: '1:364797245022:web:4a6c75ddad6ae81edc66cf',
    messagingSenderId: '364797245022',
    projectId: 'todo-firestore-93c06',
    authDomain: 'todo-firestore-93c06.firebaseapp.com',
    storageBucket: 'todo-firestore-93c06.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvs0nnPIxnqzn23MAA8rTwSGUqTZSDr4o',
    appId: '1:364797245022:android:1f4485bfd740216ddc66cf',
    messagingSenderId: '364797245022',
    projectId: 'todo-firestore-93c06',
    storageBucket: 'todo-firestore-93c06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnDQ-zu8QieFXoboUVifu3AMggyX68tW8',
    appId: '1:364797245022:ios:ec9ba795082403fcdc66cf',
    messagingSenderId: '364797245022',
    projectId: 'todo-firestore-93c06',
    storageBucket: 'todo-firestore-93c06.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnDQ-zu8QieFXoboUVifu3AMggyX68tW8',
    appId: '1:364797245022:ios:0d1cbd7bca7cf6e2dc66cf',
    messagingSenderId: '364797245022',
    projectId: 'todo-firestore-93c06',
    storageBucket: 'todo-firestore-93c06.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
